version: "3"
services:
  jmeter:
    build: ./IC_Artifact/
    container_name: jmeter
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 80:3000
    networks:
      - grafana_network
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - 443:8086
    networks:
      - grafana_network
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=jmeter
      - INFLUXDB_USER=ICPuser
      - INFLUXDB_USER_PASSWORD=ICPpass
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
networks:
  grafana_network:
volumes:
  grafana_data:
  influxdb_data:
