version: "3"
services:
  frontend:
    image: frontend
    container_name: webUI
    ports:
      - 3000:3000
    depends_on: -jmeter

  jmeter:
    image: jmeterserver
    container_name: jmeter
    ports: -5000:5008
    depends_on:
      - influxdb
      - grafana

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 80:3000
    networks:
      - grafana_network
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana.ini:/usr/share/grafana/conf/custom.ini
      - ./grafana.ini:/usr/share/grafana/conf/sample.ini
    environment:
      - GF_INSTALL_PLUGINS=cloudspout-button-panel
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:1.8.4
    container_name: influxdb
    restart: always
    ports:
      - 443:8086
    networks:
      - grafana_network
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=jmeter
      - INFLUXDB_USER=ICPuser
      - INFLUXDB_USER_PASSWORD=ICPpass
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
networks:
  grafana_network:
volumes:
  grafana_data:
  influxdb_data:
